version: '3.1'
services:
  redis:
    image: "redis:alpine"
    ports:
      - '6379:6379'
    networks:
      - backend
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: local
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  backend:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres:
